### PR TITLE
Interactive TypeScript Notebooks in Daytona with Srcbook

### PR DESCRIPTION
**Pull request by oreoluwa212**
## Writer's Checklist
/claim #51 
[Click to watch demo](https://www.loom.com/share/b02597adcce141bda752d09364ca3d13)
[link to srcbooks devcontainer repo](https://github.com/oreoluwa212/srcbooks-devcontainer)

### Writing Structure
- [x] Use short sentences and paragraphs, and include bucket brigades.
- [x] Include more than two descriptive H2 headings to organize content.
- [x] Capitalize headings according to the AP Stylebook ([use this tool](https://capitalizemytitle.com/style/AP/))
- [x] Include an introduction with at least two paragraphs before the first H2 section.
- [x] Use appropriate formatting (bold, italic, underline), notes, quotes, TLDRs, and key points.
- [x] Incorporate `code elements` and `Markdown format` where appropriate.
- [x] Ensure at least one visual element per “screen” of the article (screenshots, diagrams, tables, graphs, lists, sidenotes, blockquotes).

### Fact-Checking
- [x] Verify all facts and data points included in the article.

### Asset Management
- [x] Save images in the `/assets` folder.
- [x] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.
- [x] Optional) Create a GitHub repo for the code referenced in the article and share it.
- [x] (Optional) Include a link to this Loom video in the PR comments.

### Review and Edit
- [x] Run the draft through [Grammarly](https://grammarly.com) or a similar grammar tool.
- [x] Double-check adherence to the style guide and repository guidelines.
- [x] Use the name of the article for the title of the PR.

### CODE REVIEW

**Comment by oreoluwa212** [comment]
@nkkko kindly review

**Comment by oreoluwa212** [comment]
@nkkko Issue has been worked out and documentation is ready for review

**Comment by oreoluwa212** [comment]
@nkkko Thank you for your review in anticipation
I would like to know if I'm allowed to submit another PR I worked on (#34 ), I am done with it but I don't know if I am to also add all my details like I did on this branch. I'm concerned about repetitive files in the assets and authors folder. I await your response. Thanks

**Comment by oreoluwa212** [comment]
@nkkko

**Comment by oreoluwa212** [comment]
@mojafa  been ready for review. Kindly check. Thank you

**Comment by oreoluwa212** [comment]
@mojafa @nkkko

**Comment by mojafa** [comment]
You've submitted 2 PRs, let's close one successfully first.


This one: https://github.com/daytonaio/content/pull/108#pullrequestreview-2435997372

**Comment by oreoluwa212** [comment]
> You've submitted 2 PRs, let's close one successfully first.
> 
> This one: [#108 (review)](https://github.com/daytonaio/content/pull/108#pullrequestreview-2435997372)

duly noted

**Comment by oreoluwa212** [comment]
@mojafa the other PR has been merged successfully

**Comment by mojafa** [comment]
@oreoluwa212 your guide works well but somewhat misses to address the PR. [https://github.com/daytonaio/content/issues/51](url)

- Using Daytona to create and run a Srcbook project
- Tips for effective use of Srcbook in a Daytona environment


please add some sample code to run a test. The current project juts has the devcontainer.json file. I'd like to see some mini project.

Equally, please share tips for effective use of srcbook in a Daytona environment. 

Screenshot 2024-11-20 at 23 14 03

**Comment by oreoluwa212** [comment]
> @oreoluwa212 your guide works well but somewhat misses to address the PR. [https://github.com/daytonaio/content/issues/51](url)
> 
> * Using Daytona to create and run a Srcbook project
> * Tips for effective use of Srcbook in a Daytona environment
> 
> please add some sample code to run a test. The current project juts has the devcontainer.json file. I'd like to see some mini project.
> 
> Equally, please share tips for effective use of srcbook in a Daytona environment.
> 
> Screenshot 2024-11-20 at 23 14 03

Thank you for your feedback, getting into addressing them now

**Comment by mojafa** [comment]
No worries

**Comment by mojafa** [comment]
@oreoluwa212 any updates?

**Comment by oreoluwa212** [comment]
I am stuck at the clause of having a mini typescript project in the same folder where devcontainer is, given that the whole point of srcbook is to use this tool (AI) to generate js/ts code

**Comment by oreoluwa212** [comment]
Or can I build a mini app (not necessarily in the repo) using the launched srcbook using Daytona, will this count? @mojafa

**Comment by mojafa** [comment]
@oreoluwa212 did you add 

> Tips for effective use of Srcbook in a Daytona environment

**Comment by oreoluwa212** [comment]
> @oreoluwa212 did you add
> 
> > Tips for effective use of Srcbook in a Daytona environment

yes, PR has been updated, kindly review @mojafa

**Comment by mojafa** [comment]
@oreoluwa212 I wanted to let you know that I've just pushed some changes to the main branch that fix some linting issues and update the compliance rules. These updates should help you pass the content compliance checks in your current pull request.

When you get a chance, please pull the latest changes from the main branch into your working branch. This should make the integration smoother and help avoid any potential conflicts.

**Comment by mojafa** [comment]
Hey @oreoluwa212 this is a goood one!

I was able to run everything as expected. 

Just a slight issue though.

- Please add this as a screenshot on how to forward ports from the remote container. SOme users might struggle to get to the srcbook site

Screenshot 2024-12-05 at 02 27 39

- You missed this bit where it asks users to add api_keys from this different ai tools
Screenshot 2024-12-05 at 02 27 17

- Add a screenshot for this as well. Like an example of your code working in the srcbook
Screenshot 2024-12-05 at 02 31 48

**Comment by oreoluwa212** [comment]
> @oreoluwa212 I wanted to let you know that I've just pushed some changes to the main branch that fix some linting issues and update the compliance rules. These updates should help you pass the content compliance checks in your current pull request.
> 
> When you get a chance, please pull the latest changes from the main branch into your working branch. This should make the integration smoother and help avoid any potential conflicts.

Thank you, Jafa. I'm implementing this asap

**Comment by mojafa** [comment]
@oreoluwa212 This branch has conflicts that must be resolved. 
Alos it's failing content comapliance check. 

Let's fix those as well.

**Comment by oreoluwa212** [comment]
Yes, changes coming up in a bit

**Comment by oreoluwa212** [comment]
> @oreoluwa212 This branch has conflicts that must be resolved. Alos it's failing content comapliance check.
> 
> Let's fix those as well.

@mojafa these changes have been implemented, kindly review

**Comment by mojafa** [comment]
Nice

**Comment by oreoluwa212** [comment]
@mojafa any issues with PR?

**Pull request merged**
