### PR TITLE
Guide: Semantic Browser History Search with ChromaDB and Embeddings

### PR DESCRIPTION
**Pull request by onyedikachi-david**
/claim #11
fixes: #11
# Pull Request Template

## Writer's Checklist

- [ ] **Follow Writing Structure**
  - [ ] I have used more than two H2 subtitles to organize content.
  - [ ] Include an introduction with at least two paragraphs before the first H2 section.
  - [ ] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [ ] Include `code elements` where appropriate.
  - [ ] Write the article in Markdown format.

- [ ] **Fact-Check**
  - [ ] I have verified all facts and data points included in the article.

- [ ] **Assets**
  - [ ] Save images in the `/assets` folder.
  - [ ] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [ ] **Interlinking**
  - [ ] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [ ] Interlink keywords using the appropriate URLs.

- [ ] **Glossary/Definitions**
  - [ ] Identify and mark new terms that could be added to the Definitions page.

- [ ] **Review and Edit**
  - [ ] Read the article out loud to catch any awkward phrasing.
  - [ ] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [ ] Double-check adherence to the style guide and repository guidelines.

### CODE REVIEW

**Comment by mojafa** [comment]
Please implement the full checklist. Add at least one definition, author, etc. Please follow the instructions in the readme.

**Comment by mojafa** [comment]
@onyedikachi-david please share an update. Rename the PR to match the issue, and follow the [CONTRIBUTING.md](https://github.com/daytonaio/content/blob/main/CONTRIBUTING.md).

**Comment by onyedikachi-david** [comment]
On it. @mojafa

**Comment by onyedikachi-david** [comment]
@mojafa , please review.

**Comment by mojafa** [comment]
@onyedikachi-david 

Please use this resources as inspiration for format of the guide as per the issue:

1. https://github.com/nkkko/history
2. https://www.daytona.io/dotfiles/how-to-set-up-a-project-with-cal-com-and-supabase

I don't think you need this:

Screenshot 2024-12-05 at 03 03 44

This is a supposed to be a technical guide, I dont think this format sits well. Please refer to the resources shared. Juts make look at this [article](https://www.daytona.io/dotfiles/how-to-set-up-a-project-with-cal-com-and-supabase ) and go deeper on it.

Screenshot 2024-12-05 at 03 05 41


Please share screenshots here
Screenshot 2024-12-05 at 03 07 52

Also here share screenshots. Like actually run the code and the commands and share your terninal outputs. Your outputs are text, need that as screenshots of your prompts.
Screenshot 2024-12-05 at 03 08 33


Are you sure this is a guide?
Screenshot 2024-12-05 at 03 11 29

**Comment by mojafa** [comment]
@onyedikachi-david good stuff man. Just that command correction and we're good

**Comment by mojafa** [comment]
Screenshot 2024-12-09 at 11 38 16

**Comment by mojafa** [comment]
@onyedikachi-david apologies, someone else was intiially assigned this issue and their PR was opened before yours. Please allow me to close this PR. Please tackle another issue.

**Comment by mojafa** [comment]
@onyedikachi-david apologies, someone else was intiially assigned this issue and their PR was opened before yours. Please allow me to close this PR. Please feel free to tackle another issue.

**Pull request closed without merging**
