### PR TITLE
Building a Link Shortener with FastHTML and Dub.co

### PR DESCRIPTION
**Pull request by Titre123**
/claim #50

### Writing Structure

- [ ] Use short sentences and paragraphs, and include bucket brigades.
- [ ] Include more than two descriptive H2 headings to organize content.
- [ ] Capitalize headings according to the AP Stylebook
      ([use this tool](https://capitalizemytitle.com/style/AP/))
- [ ] Include an introduction with at least two paragraphs before the first H2
      section.
- [ ] Use appropriate formatting (bold, italic, underline), notes, quotes,
      TLDRs, and key points.
- [ ] Incorporate `code elements` and `Markdown format` where appropriate.
- [ ] Ensure at least one visual element per “screen” of the article
      (screenshots, diagrams, tables, graphs, lists, sidenotes, blockquotes).

### Fact-Checking

- [ ] Verify all facts and data points included in the article.

### Asset Management

- [ ] Save images in the `/assets` folder.
- [ ] Follow naming conventions:
      `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.
- [ ] (Optional) Create a GitHub repo for the code referenced in the article and
      share it.
- [ ] (Optional) Include a link to this Loom video in the PR comments.

### Interlinking

- [ ] Use `CTRL+F` to search for relevant keywords in:
  - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
  - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
- [ ] Interlink keywords using the appropriate URLs.

### Glossary/Definitions

- [ ] Create new definition in `/defitnitions` folder.

### Review and Edit

- [ ] Ensure articles address the needs of the target audience and their search
      intent.
- [ ] Read the article out loud to catch any awkward phrasing.
- [ ] Run the draft through [Grammarly](https://grammarly.com) or a similar
      grammar tool.
- [ ] Double-check adherence to the style guide and repository guidelines.
- [ ] Use the name of the article for the title of the PR.

### CODE REVIEW

**Comment by mojafa** [comment]
@Titre123 PR fails DCO checks.

**Comment by mojafa** [comment]
Pleasee follow steps below:
Screenshot 2024-12-07 at 00 53 44

**Comment by Titre123** [comment]
I am getting an error due to the naming of this due the the naming of this
file

**Comment by mojafa** [comment]
sorry?

**Comment by Titre123** [comment]
What can I do about this

**Comment by Titre123** [comment]
I have fixed it. I had to use my ubuntu terminal instead

**Comment by mojafa** [comment]
@Titre123 good stuff so far, but can you restructre the bit to create a project from scratch.


so tell a reader to md `dub-fasthtml-shortener` , then cd `dub-fasthtml-shortener`, then create `requirements.txt`add the packages and dependiencies, `main.py`, `.env`, .`devcontainer/devconatiner.json`......


create a repo on giothub, push your code ,


then go to termianl and do Daytona create [your_repo_url]..... then the rest

**Comment by mojafa** [comment]
I've assigned the issue to you already, so no worries

**Comment by mojafa** [comment]
Screenshot 2024-12-08 at 01 31 18
also don't forget this

**Comment by mojafa** [comment]
REfer here: https://github.com/daytonaio/content/blob/main/guides/20240827_setup_mongodb_daytona_playground.md

**Comment by Titre123** [comment]
Thanks, I'll check it out.

**Comment by mojafa** [comment]
@Titre123 any updates?

**Pull request closed without merging**
