### PR TITLE
Added Fly-Provider Docs

### PR DESCRIPTION
**Pull request by scshiv29-dev**
/claim #79 

### Writing Structure
- [x] Use short sentences and paragraphs, and include bucket brigades.
- [x] Include more than two descriptive H2 headings to organize content.
- [x] Capitalize headings according to the AP Stylebook ([use this tool](https://capitalizemytitle.com/style/AP/))
- [x] Include an introduction with at least two paragraphs before the first H2 section.
- [x] Use appropriate formatting (bold, italic, underline), notes, quotes, TLDRs, and key points.
- [x] Incorporate `code elements` and `Markdown format` where appropriate.
- [x] Ensure at least one visual element per “screen” of the article (screenshots, diagrams, tables, graphs, lists, sidenotes, blockquotes).

### Fact-Checking
- [x] Verify all facts and data points included in the article.

### Asset Management
- [x] Save images in the `/assets` folder.
- [x] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.
- [x] (Optional) Create a GitHub repo for the code referenced in the article and share it.
- [x] (Optional) Include a link to this Loom video in the PR comments.

### Interlinking
- [x] Use `CTRL+F` to search for relevant keywords in:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
- [x] Interlink keywords using the appropriate URLs.

### Glossary/Definitions
- [x] Create new definition in `/defitnitions` folder.

### Review and Edit
- [x] Ensure articles address the needs of the target audience and their search intent.
- [x] Read the article out loud to catch any awkward phrasing.
- [x] Run the draft through [Grammarly](https://grammarly.com) or a similar grammar tool.
- [x] Double-check adherence to the style guide and repository guidelines.
- [x] Use the name of the article for the title of the PR.

### CODE REVIEW

**Review by mojafa — APPROVED** [review]
versions are not marked alpha anymore. Review the version number and update.

**Review by mojafa — CHANGES_REQUESTED** [review]
Please test that creating your first workspace works. The command to create a workspace doesn't seem to be working. The flag --provider no longer works.

**Comment by mojafa** [comment]
[Daytona Provider Documentation](https://daytona.io/docs/providers), this link is no longer valid as well

**Comment by scshiv29-dev** [comment]
> versions are not marked alpha anymore. Review the version number and update.

image

When I do provider install I am still seeing alpha versions

**Comment by mojafa** [comment]
Screenshot 2024-11-11 at 16 34 02

**Comment by mojafa** [comment]
Please check your versions again, uninstall and reinstall

**Comment by mojafa** [comment]
Screenshot 2024-11-11 at 19 17 26

**Comment by mojafa** [comment]
Hey please review the section: Creating Your First Workspace. The commands still don't work

**Comment by mojafa** [comment]
Equally, the command to list a workspace is `daytona list` not `daytona workspace list`

**Comment by mojafa** [comment]
@scshiv29-dev almost done, just remove the '-t fly' in these commands:
1. **From a Git Repository**:
```bash
daytona create https://github.com/daytonaio/content --name workspacename -t fly
```

2. **With Custom Image**:
```bash
daytona create  https://github.com/daytonaio/content  --custom-image ubuntu:latest --custom-image-user ubuntu --name workspacename -t fly
```


everything else works!

**Comment by scshiv29-dev** [comment]
@mojafa I've made the reviewed changes .

**Review by mojafa — APPROVED** [review]
This PR meets the requirements @nkkko

**Review by nkkko — APPROVED** [review]

**Pull request merged**
