### PR TITLE
Feat: Article for using phi-3 and .NET development in Daytona

### PR DESCRIPTION
**Pull request by dheerajsingh89**
/claim #49
Fixes : #49 

### Writing Structure
- [x] Use short sentences and paragraphs, and include bucket brigades.
- [x] Include more than two descriptive H2 headings to organize content.
- [x] Capitalize headings according to the AP Stylebook ([use this tool](https://capitalizemytitle.com/style/AP/))
- [x] Include an introduction with at least two paragraphs before the first H2 section.
- [x] Use appropriate formatting (bold, italic, underline), notes, quotes, TLDRs, and key points.
- [x] Incorporate `code elements` and `Markdown format` where appropriate.
- [x] Ensure at least one visual element per “screen” of the article (screenshots, diagrams, tables, graphs, lists, sidenotes, blockquotes).

### Fact-Checking
- [x] Verify all facts and data points included in the article.

### Asset Management
- [x] Save images in the `/assets` folder.
- [x] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.
- [ ] (Optional) Create a GitHub repo for the code referenced in the article and share it.
- [ ] (Optional) Include a link to this Loom video in the PR comments.

### Interlinking
- [x] Use `CTRL+F` to search for relevant keywords in:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
- [ ] Interlink keywords using the appropriate URLs.

### Glossary/Definitions
- [ ] Create new definition in `/defitnitions` folder.

### Review and Edit
- [x] Ensure articles address the needs of the target audience and their search intent.
- [x] Read the article out loud to catch any awkward phrasing.
- [x] Run the draft through [Grammarly](https://grammarly.com) or a similar grammar tool.
- [x] Double-check adherence to the style guide and repository guidelines.
- [x] Use the name of the article for the title of the PR.

### CODE REVIEW

**Comment by mojafa** [comment]
@itsdheerajdp Here's my review:

-  Rename this PR to match the issue title: Using Phi-3 and .NET Development in Daytona 

- Your article has no references, please add them.

- You jumped straight to Creating devcontainer.json, I don't see anywhere `daytona` commands are used. you've jumpked this step: 

> `Step-by-step guide to setting up a .NET environment in Daytona using devcontainer.json`

-  I was expecting to create a project say a github repo, then a .devcontainer, then a devcontainer.json, then `daytona create...` then having my IDE open up. That's where i create my dockerfile, run and test Phi-3.5 Labs Samples. 

 - I understand the use of the flow, but also please include screenshots of how the project runs on your machine. 
 - Also include this last step from the issue : 
> Advantages of this setup for collaborative AI development and experimentation

**Comment by mojafa** [comment]
I've assigned this issue to you. 

Here's the PR: [https://github.com/daytonaio/content/issues/49](url)

**Comment by itsdheerajdp** [comment]
@mojafa sure I'll do that

**Comment by mojafa** [comment]
@itsdheerajdp any updates?

**Comment by mojafa** [comment]
@itsdheerajdp any progress?

**Comment by itsdheerajdp** [comment]
@mojafa these days i'm busy with some other work. You can allow others as well to work on the PR

**Comment by mojafa** [comment]
@dheerajsingh89 I'm sorry, I'll have to close this PR.

you had already submitted a [PR](https://github.com/daytonaio/content/pull/42) earlier  that aimed to solve this [issue](https://github.com/daytonaio/content/issues/35). I have assigend it to you as it came earlier. Please let's focus on gettting that across the line.

You can always reopen this PR and tackle the issue or any other isses after we successfully merge https://github.com/daytonaio/content/pull/42

We aim to have one PR per contributor. Tackling many issues at once violates the rule as per the guidelines.

Thanks.

**Pull request closed without merging**
