### PR TITLE
fix: invalid path by renaming file 

### PR DESCRIPTION
**Pull request by varshith257**
This PR resolves an issue caused by a file name in the repository containing an unsupported character (#). The file `articles/20240828_Daytona_Office_Hours_#8:_Latest_Updates_and_Highlights.md` was renamed to `articles/20240828_Daytona_Office_Hours_8_Latest_Updates_and_Highlights.md` to ensure compatibility with Windows and other filesystems.

### CODE REVIEW

**Comment by varshith257** [comment]
@nkkko This needs to be merged ASAP as it is making trouble to clone the repository locally on Windows due to an invalid character 
Please review and merge this fix to prevent further path-related issues

**Comment by mojafa** [comment]
@varshith257 what do you mean? 
We have #9 as well. How is it affecting your PR?

**Comment by mojafa** [comment]
I had made an update to fix lint issues and compliance checks. 

Please would again and make changes

**Comment by varshith257** [comment]
@mojafa The issue is that I can't clone the repo due to invalid character name in a path for Windows. While receiving objects from upstream it getting terminate with error of unsupported character

**Comment by mojafa** [comment]
@nkkko Please look into this

**Comment by nkkko** [comment]
tnx

**Pull request merged**
