### PR TITLE
docs(guide): Add guide for setting up DuckDB playground with Daytona

### PR DESCRIPTION
**Pull request by onyedikachi-david**
/claim #57
Fixes: #57

# Pull Request Template

## Writer's Checklist

- [x] **Follow Writing Structure**
  - [x] I have used more than two H2 subtitles to organize content.
  - [x] Include an introduction with at least two paragraphs before the first H2 section.
  - [x] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [x] Include `code elements` where appropriate.
  - [x] Write the article in Markdown format.

- [x] **Fact-Check**
  - [x] I have verified all facts and data points included in the article.

- [ ] **Assets**
  - [ ] Save images in the `/assets` folder.
  - [ ] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [ ] **Interlinking**
  - [ ] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [ ] Interlink keywords using the appropriate URLs.

- [ ] **Glossary/Definitions**
  - [ ] Identify and mark new terms that could be added to the Definitions page.

- [x] **Review and Edit**
  - [x] Read the article out loud to catch any awkward phrasing.
  - [x] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [x] Double-check adherence to the style guide and repository guidelines.

### CODE REVIEW

**Comment by onyedikachi-david** [comment]
@nkkko Please review sir.

**Comment by mojafa** [comment]
@onyedikachi-david there's an issue with your devcontainer configs. see below:
Screenshot 2024-11-21 at 00 08 16

**Comment by mojafa** [comment]
Equally please:

-  add screenshots of some of the steps thag run successfully.
- add your author information and updtae the assets
- Rename the PR to match the issue name

**Comment by mojafa** [comment]
@onyedikachi-david any updates?

**Comment by onyedikachi-david** [comment]
Sorry for not responding all this while, been busy with work and all that. I'll leave it for @c0d33ngr to finish, as he has made reasonable progress. What do you think?

**Comment by mojafa** [comment]
@onyedikachi-david Ok, I'll close this PR. Yopu can tackle any of the other issues. I also see there's some other PRs you've raised, I'll rereview them

**Pull request closed without merging**
