### PR TITLE
Introducing Daytona Project Config: Simplify and Streamline Workspace…

### LINKED ISSUE #33: daytona project-config feature explained
### Content Type

Article

### Article Description

Write an article to introduce a daytona project-config feature. Use up to 2 screenshots, code snippets and sample repo (can be existing one) for which you will create project-config.

### Target Audience

individual dev

### References/Resources

_No response_

### Examples

_No response_

### Special Instructions

_No response_

### PR DESCRIPTION
**Pull request by divanshu-go**
Introducing Daytona Project Config: Simplify and Streamline Workspace…
/claim #33 
Closes #33

### Writing Structure
- [x] Use short sentences and paragraphs, and include bucket brigades.
- [x] Include more than two descriptive H2 headings to organize content.
- [x] Capitalize headings according to the AP Stylebook ([use this tool](https://capitalizemytitle.com/style/AP/))
- [x] Include an introduction with at least two paragraphs before the first H2 section.
- [x] Use appropriate formatting (bold, italic, underline), notes, quotes, TLDRs, and key points.
- [x] Incorporate `code elements` and `Markdown format` where appropriate.
- [ ] Ensure at least one visual element per “screen” of the article (screenshots, diagrams, tables, graphs, lists, sidenotes, blockquotes).

### Fact-Checking
- [x] Verify all facts and data points included in the article.

### Asset Management
- [x] Save images in the `/assets` folder.
- [x] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.
- [ ] (Optional) Create a GitHub repo for the code referenced in the article and share it.
- [ ] (Optional) Include a link to this Loom video in the PR comments.

### Interlinking
- [x] Use `CTRL+F` to search for relevant keywords in:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
- [x] Interlink keywords using the appropriate URLs.

### Glossary/Definitions
- [ ] Create new definition in `/defitnitions` folder.

### Review and Edit
- [x] Ensure articles address the needs of the target audience and their search intent.
- [x] Read the article out loud to catch any awkward phrasing.
- [ ] Run the draft through [Grammarly](https://grammarly.com) or a similar grammar tool.
- [x] Double-check adherence to the style guide and repository guidelines.
- [x] Use the name of the article for the title of the PR.

### CODE REVIEW

**Comment by mojafa** [comment]
@divanshu-go please fix the broken link in the reference section

**Comment by mojafa** [comment]
Also, could you please provide screenshots instead of terminal results as text? Like this:

Screenshot 2024-11-17 at 18 42 51


The issue explicitly asks to use up to 2 screenshots, code snippets etc. See here: [https://github.com/daytonaio/content/issues/33] . 


Your article meets almost all the requirements, though.

**Comment by divanshu-go** [comment]
@mojafa thanks for the review . I will get back to you after doing changes

**Comment by divanshu-go** [comment]
@mojafa did the requested changes .

**Comment by mojafa** [comment]
@divanshu-go a little heads up your article is 84% AI generated. Please put some more efforrt, paraphrase at least.

Screenshot 2024-11-21 at 21 58 16

**Comment by mojafa** [comment]
I will proceed and test it out, but expect you to have fixed the plagarism/AI generated issue.

**Comment by divanshu-go** [comment]
image

**Comment by divanshu-go** [comment]
Para phrasing the whole article will take some time. I will notify you when I think it is up to the mark

**Comment by mojafa** [comment]
Below 50% should be ok

**Comment by divanshu-go** [comment]
@mojafa Is this fine now?
image

**Comment by mojafa** [comment]
@divanshu-go yes it is!

**Review by mojafa — APPROVED** [review]

**Comment by mojafa** [comment]
@nkkko PR meets requirements.

**Pull request merged**
