### PR TITLE
Feat: Should you only use a devcontainer, or do you also need a Dockerfile? What about Docker Compose? 

### PR DESCRIPTION
**Pull request by dheerajsingh89**
/claim #32
Fixes: #32 

# Pull Request Template

## Writer's Checklist

- [x] **Follow Writing Structure**
  - [x] I have used more than two H2 subtitles to organize content.
  - [x] Include an introduction with at least two paragraphs before the first H2 section.
  - [x] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [x] Include `code elements` where appropriate.
  - [x] Write the article in Markdown format.

- [x] **Fact-Check**
  - [x] I have verified all facts and data points included in the article.

- [x] **Assets**
  - [x] Save images in the `/assets` folder.
  - [x] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [x] **Interlinking**
  - [x] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [x] Interlink keywords using the appropriate URLs.

- [x] **Glossary/Definitions**
  - [x] Identify and mark new terms that could be added to the Definitions page.

- [x] **Review and Edit**
  - [x] Read the article out loud to catch any awkward phrasing.
  - [x] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [x] Double-check adherence to the style guide and repository guidelines.

### CODE REVIEW

**Review by nkkko — CHANGES_REQUESTED** [review]
This is not bad. Where have you sourced images from? Please replace the last box "Dev Container" and write in it "Dev Environment" instead VS Code write Daytona.

Please before proceeding make sure that you have followed every step in the readme and implemented checklist. Read everything slowly and do edits if needed.

Thanks!

**Comment by itsdheerajdp** [comment]
@nkkko I made the requested changes , kindly go through it ...

**Comment by oreoluwa212** [comment]
@nkkko This is yet to be assigned to @itsdheerajdp 
is the issue still available for grabs?

**Comment by mojafa** [comment]
@itsdheerajdp , almost there.

how about something like this:
```
Introduction to Development Environments
What is a DevContainer?
- Key Features:
- Use Cases:
Understanding Dockerfile
- Key Features:
- Use Cases:
Exploring Docker Compose
- Key Features:
- Use Cases:
When to Use Each Tool
Combining DevContainers, Dockerfiles, and Docker Compose
Code Examples
* DevContainer Configuration (devcontainer.json)
* Dockerfile Example
* Docker Compose Example (docker-compose.yml)
Diagrams and Illustrations
Comparison Table
Conclusion
```

Your diagrams and illustration need in-depth architecture of these tools. These are just screenshots from chatgpt, but check medium or some articles that go indepth on them and may be cite them as sources as well. also explain what is inluded in the dockerfile, compose file and devcotainer.json. a line-by-line example

Screenshot 2024-12-09 at 10 53 10
Screenshot 2024-12-09 at 10 53 15
Screenshot 2024-12-09 at 10 53 22

**Comment by itsdheerajdp** [comment]
> @itsdheerajdp , almost there.
> 
> how about something like this:
> 
> ```
> Introduction to Development Environments
> What is a DevContainer?
> - Key Features:
> - Use Cases:
> Understanding Dockerfile
> - Key Features:
> - Use Cases:
> Exploring Docker Compose
> - Key Features:
> - Use Cases:
> When to Use Each Tool
> Combining DevContainers, Dockerfiles, and Docker Compose
> Code Examples
> * DevContainer Configuration (devcontainer.json)
> * Dockerfile Example
> * Docker Compose Example (docker-compose.yml)
> Diagrams and Illustrations
> Comparison Table
> Conclusion
> ```
> 
> Your diagrams and illustration need in-depth architecture of these tools. These are just screenshots from chatgpt, but check medium or some articles that go indepth on them and may be cite them as sources as well. also explain what is inluded in the dockerfile, compose file and devcotainer.json. a line-by-line example
> 
> Screenshot 2024-12-09 at 10 53 10 Screenshot 2024-12-09 at 10 53 15 Screenshot 2024-12-09 at 10 53 22

It'll be good @mojafa but i'm busy these days with some personal projects. You can allow others as well if they want to collaborate.

**Comment by mojafa** [comment]
@dheerajsingh89  I'm closing this PR as you have 2 other open PRs. I'll assign you the one i think is almost near the finish line.

**Pull request closed without merging**
