### PR TITLE
Add gpu utilization guide

### LINKED ISSUE #8: GPU Utilization in Containerized Environments
### Content Type

Article

### Article Description

- How to set up and configure containers for GPU-intensive tasks such as LLM inference or fine-runing.
- Demo project as example and proof of work.
- Discussion on common challenges and solutions.
- OPTIONAL: Performance benchmarks and optimization tips.

### Target Audience

Devs playing with LLM inference

### References/Resources

_No response_

### Examples

[Example project that should run in Daytona](https://github.com/karpathy/nanoGPT)

### Special Instructions

_No response_

### PR DESCRIPTION
**Pull request by giraffekey**
# GPU Utilization Guide

/claim #8 
/closes #8 

## Writer's Checklist

- [x] **Follow Writing Structure**
  - [x] I have used more than two H2 subtitles to organize content.
  - [x] Include an introduction with at least two paragraphs before the first H2 section.
  - [x] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [x] Include `code elements` where appropriate.
  - [x] Write the article in Markdown format.

- [x] **Fact-Check**
  - [x] I have verified all facts and data points included in the article.

- [x] **Assets**
  - [x] Save images in the `/assets` folder.
  - [x] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [x] **Interlinking**
  - [x] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [x] Interlink keywords using the appropriate URLs.

- [x] **Glossary/Definitions**
  - [x] Identify and mark new terms that could be added to the Definitions page.

- [x] **Review and Edit**
  - [x] Read the article out loud to catch any awkward phrasing.
  - [x] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [x] Double-check adherence to the style guide and repository guidelines.

### CODE REVIEW

**Comment by nkkko** [comment]
You haven't linked this PR to the issue.

**Review by nkkko — COMMENTED** [review]
have you tested this? could you record a short video, maybe using loom or any screen recording software?

it should work with daytona also!

thanks!

**Comment by giraffekey** [comment]
https://github.com/user-attachments/assets/0ef3a0a3-03a2-4e5d-8ba7-99cd1add9dd4

**Comment by mojafa** [comment]
@giraffekey Please link this PR to the issue. Close this PR and create a new PR.

**Comment by mojafa** [comment]
@giraffekey Plese fix this, the PR fails DCO checks

**Comment by giraffekey** [comment]
> @giraffekey Plese fix this, the PR fails DCO checks

Hi, I opened a new one.

**Pull request closed without merging**
