### PR TITLE
Setting Up a MongoDB Playground with Daytona

### PR DESCRIPTION
**Pull request by stdthoth**
/claim #53 
Closes issue #53 

### Writing Structure
- [x] Use short sentences and paragraphs, and include bucket brigades.
- [x] Include more than two descriptive H2 headings to organize content.
- [x] Capitalize headings according to the AP Stylebook ([use this tool](https://capitalizemytitle.com/style/AP/))
- [x] Include an introduction with at least two paragraphs before the first H2 section.
- [x] Use appropriate formatting (bold, italic, underline), notes, quotes, TLDRs, and key points.
- [x] Incorporate `code elements` and `Markdown format` where appropriate.
- [x] Ensure at least one visual element per “screen” of the article (screenshots, diagrams, tables, graphs, lists, sidenotes, blockquotes).

### Fact-Checking
- [x] Verify all facts and data points included in the article.

### Asset Management
- [x] Save images in the `/assets` folder.
- [x] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.
- [x] (Optional) Create a GitHub repo for the code referenced in the article and share it.
- [ ] (Optional) Include a link to this Loom video in the PR comments.

### Interlinking
- [ ] Use `CTRL+F` to search for relevant keywords in:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
- [ ] Interlink keywords using the appropriate URLs.

### Glossary/Definitions
- [ ] Create new definition in `/defitnitions` folder.

### Review and Edit
- [x] Ensure articles address the needs of the target audience and their search intent.
- [x] Read the article out loud to catch any awkward phrasing.
- [x] Run the draft through [Grammarly](https://grammarly.com) or a similar grammar tool.
- [x] Double-check adherence to the style guide and repository guidelines.
- [x] Use the name of the article for the title of the PR.

### CODE REVIEW

**Comment by mojafa** [comment]
@stdthoth your guide meets all the requirements and works well. To finalise on this please check that your commit messages include a signed-off by...

See below:

Screenshot 2024-11-13 at 19 23 50


You could close this PR and resubmit as well.

**Comment by mojafa** [comment]
@nkkko @stdthoth I was able to actually run the MongoDB Playground with Daytona.

The guide covers everything well. Just a few suggestions below.

But a few hurdles I had to overcome:

- `daytona target set` needed to be docker

- @nkkko  **just an observation**: I had Cursor installed and had the `code` command set to open Cursor so everytime i ran ` daytona create https://github.com/mojafa/daytona-mongo-db.git` it would be fatal because Daytona expects `code` to open VSCode for it to install Remote-SSH.

- the mongo image i used was `FROM ubuntu:focal` and not `FROM mcr.microsoft.com/devcontainers/base:focal` a few issues regarding a compatible base image.
 
- had to add the `mongo-playground` extension once on the remote image. This enabled me to run the queries to test MongoDB. Equally, might have had to `docker exec -it` the mongo image. 


Screenshot 2024-11-13 at 20 23 36

**Comment by nkkko** [comment]
@mojafa cursor with code cli is plain wrong :-) 
what are the next steps for @stdthoth

**Comment by stdthoth** [comment]
@mojafa i will add those hurdles which you overcame to the troubleshooting section of the article and I'll try switching the image and see if it still works for me (might be a version thing since I am still on an early release).. appreciate the response and assignment 🙏🏼

**Comment by mojafa** [comment]
@stdthoth your guide meets most of the requirements and works well. To finalise on this, please check that your commit messages include a signed-off by...

See below:
Screenshot 2024-11-17 at 19 00 06

**Comment by mojafa** [comment]
@stdthoth  please ensure you meet the DCO check, your commit messages should include a signed-off by...

**Comment by mojafa** [comment]
@stdthoth any updates? your PR is almost there. Please fix DCO checks, and include the changes requested.

**Comment by stdthoth** [comment]
@mojafa i'm on it... will be done by tomorrow

**Comment by mojafa** [comment]
Thank you

**Review by mojafa — APPROVED** [review]
This PR meets all requreiments

**Comment by stdthoth** [comment]
@mojafa fixed DCO issues and added ways to overcome hurdles to common issues and troubleshooting section

**Comment by nkkko** [comment]
Thanks @stdthoth  for your work!

You can showcase your contribution on your GitHub profile: https://github.com/daytonaio/content/blob/main/CONTRIBUTING.md#showcase-your-contributions

**Comment by stdthoth** [comment]
Thank you for the opportunity @nkkko

**Pull request merged**
