### PR TITLE
Feat: Omni and Claude Engineers inside Daytona

### PR DESCRIPTION
**Pull request by dheerajsingh89**
/claim #36
Fixes #36 

# Pull Request Template

## Writer's Checklist

- [x] **Follow Writing Structure**
  - [x] I have used more than two H2 subtitles to organize content.
  - [x] Include an introduction with at least two paragraphs before the first H2 section.
  - [x] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [x] Include `code elements` where appropriate.
  - [x] Write the article in Markdown format.

- [x] **Fact-Check**
  - [x] I have verified all facts and data points included in the article.

- [x] **Assets**
  - [x] Save images in the `/assets` folder.
  - [x] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [x] **Interlinking**
  - [x] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [x] Interlink keywords using the appropriate URLs.

- [x] **Glossary/Definitions**
  - [x] Identify and mark new terms that could be added to the Definitions page.

- [x] **Review and Edit**
  - [x] Read the article out loud to catch any awkward phrasing.
  - [x] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [x] Double-check adherence to the style guide and repository guidelines.

### CODE REVIEW

**Review by nkkko — CHANGES_REQUESTED** [review]
same comments as on #35 

we will accept only high quality content that has been proven it can be replicated by the reader

please read the README!

Thanks

**Comment by mojafa** [comment]
@itsdheerajdp any updates

**Comment by itsdheerajdp** [comment]
> @itsdheerajdp any updates

I'll try to update the PR

**Comment by mojafa** [comment]
@dheerajsingh89  closing as you have another open PR.

**Pull request closed without merging**
